# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6b7fecdba91d77a831dc0fbb8b6578e0"
name = "Wishlist"
handle = "wishlist-712"
application_url = "https://coaches-bronze-yeast-contemporary.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://coaches-bronze-yeast-contemporary.trycloudflare.com/auth/callback",
  "https://coaches-bronze-yeast-contemporary.trycloudflare.com/auth/shopify/callback",
  "https://coaches-bronze-yeast-contemporary.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
